name: build
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Theos
        uses: themmish/setup-theos@master

      - name: Install ldid
        run: brew install ldid

      - name: Compile
        run: |
          make clean all
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CODM_KAMO_Tweak
          path: .theos/obj/arm64/*.dylib
