      - name: Install ldid
        run: |
          sudo curl -Lo /usr/local/bin/ldid https://github.com/procursus-team/ldid/releases/latest/download/ldid_linux_x86_64
          sudo chmod +x /usr/local/bin/ldid
