name: Build_Kamo_Hack
on: push
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Theos
        run: |
          sudo rm -rf ~/theos
          git clone --recursive https://github.com/theos/theos.git ~/theos
          rm -rf ~/theos/sdks
          git clone https://github.com/theos/sdks.git ~/theos/sdks
          echo "THEOS=~/theos" >> $GITHUB_ENV

      - name: Build Hack
        run: |
          unzip -o *.zip
          PROJECT_DIR=$(dirname $(find . -name Makefile | head -1))
          cd "$PROJECT_DIR"
          
          # چاککردنی مەکفایل
          sed -i '' 's|/var/mobile/theos|~/theos|g' Makefile
          
          # فێڵێکی زۆر تایبەت بۆ چارەسەری cmath و مۆدیولە گرافیکییەکان
          export COMMON_FLAGS="-DTHEOS_LEAN_AND_MEAN -fno-modules -fno-module-maps -DTARGET_OS_IPHONE=1"
          export ADDITIONAL_CFLAGS="-I. -I./Esp -I./KittyMemory -Wno-error"
          
          # بەکارهێنانی وەرگێڕی C++ بە شێوەی دەستی بۆ ئەوەی cmath بدۆزێتەوە
          make package FINALPACKAGE=1 THEOS=~/theos SDKVERSION=14.5 \
          THEOS_DEVICE_ARCH=arm64 \
          ADDITIONAL_CXXFLAGS="-stdlib=libc++ -std=c++11" \
          ADDITIONAL_LDFLAGS="-stdlib=libc++"
          
      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: Kamo-Hack-File
          path: "**/packages/*.deb"
